steps:
  - label: ":console:"
    commands:
      - env

  - label: ":rspec:"
    artifact_paths: "tmp/rspec-*.xml"
    commands:
      - "bundle"
      - "rspec --format progress --format RspecJunitFormatter --out tmp/rspec-$BUILDKITE_JOB_ID.xml"
    plugins:
      docker#v1.0.0:
        image: "ruby:2.4"
        workdir: /app

  - wait: ~
    continue_on_failure: true

  - label: ":junit:"
    commands:
      - .buildkite/junit.sh

  - wait

  - command: ".buildkite/deploy.sh"
    label: ":rocket:"
