steps:
  - label: ":console:"
    commands:
      - env

  - label: ":rspec:"
    artifact_paths: "rspec.xml"
    commands:
      - bundle
      - rspec --format progress --format RspecJunitFormatter --out rspec.xml
    plugins:
      docker#v1.0.0:
        image: "ruby:2.4"
        workdir: /app

  - wait: ~
    continue_on_failure: true

  - label: ":junit:"
    commands:
      - bundle
      - .buildkite/junit
    artifact_paths: annotation.md
    plugins:
      docker#v1.0.0:
        image: "ruby:2.4"
        workdir: /app

  - wait

  - label: "Annotate"
    commands:
      - .buildkite/annotate.sh

  - wait

  - command: ".buildkite/deploy.sh"
    label: ":rocket:"
