steps:
  - label: ":rspec:"
    command: ".buildkite/rspec.sh"
    artifact_paths:
      - "rspec.xml"

  - wait: ~
    continue_on_failure: true

  - command: ".buildkite/junit"
    label: ":junit:"

  - wait

  - command: ".buildkite/deploy.sh"
    label: ":rocket:"
